ModelConf:
  input_shape: [28, 28, 1]
  output_shape: 10

TrainerConf:
  epochs: 10
  loss: {
          class_name: "CategoricalCrossentropy"
  }
  optimizer: {
          "identifier": "Adam"
  }

DataPreprocConf:
  classes: 10